### ISSUE TITLE
Antiforgery and subdomains

### ISSUE THREAD

**Issue by verysimplenick** [aspnet/Antiforgery#174]
Hi, I write asp.net core app that serves 2 subdomains. I change request and links generated that transfer requests subdomain to the subfolder, everything is ok, but sometimes I have troubles with anti-forgery:

```
[17:14:36 INF] Request starting HTTP/1.1 POST http://buyer.localhost/account/login application/json; charset=utf-8 53
[17:14:36 DBG] POST requests are not supported
[17:14:36 DBG] AuthenticationScheme: Identity.Application was not authenticated.
[17:14:36 DBG] Request successfully matched the route with name 'null' and template 'Account/Login'.
[17:14:36 DBG] Executing action NNN.AccountController.Login (NNN)
[17:14:36 INF] Executed action NNN.AccountController.Login (NNN) in 2.1411ms
[17:14:36 ERR] An unhandled exception has occurred while executing the request
System.InvalidOperationException: The antiforgery token could not be decrypted. ---> System.FormatException: TODO: Malformed input.
   at Microsoft.AspNetCore.WebUtilities.WebEncoders.GetNumBase64PaddingCharsToAddForDecode(Int32 inputLength)
   at Microsoft.AspNetCore.WebUtilities.WebEncoders.GetArraySizeRequiredToDecode(Int32 count)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.DeserializeTokens(HttpContext httpContext, AntiforgeryTokenSet antiforgeryTokenSet, AntiforgeryToken& cookieToken, AntiforgeryToken& requestToken)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.ValidateTokens(HttpContext httpContext, AntiforgeryTokenSet antiforgeryTokenSet)
   at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.<ValidateRequestAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.<OnAuthorizationAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NNN.SubdomainRewritingMiddleware.<Invoke>d__4.MoveNext() in q:\nyxale\NNN\project\NNN\SubdomainRewritingMiddleware.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.<Invoke>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.<Invoke>d__7.MoveNext()
```

In Startup:
```cs
            services.AddAntiforgery(options => {
                options.HeaderName = "X-XSRF-TOKEN";
            } );
```

**Comment by mkArtakMSFT** [comment]
@verysimplenick, what do you mean by "sometimes"? Does the same scenario work sometimes, and not the other times?
Also, would be great to get information about your app structure and how that maps with multiple subdomains?

**Comment by verysimplenick** [comment]
> Does the same scenario work sometimes, and not the other times?
It's strange but I can't reproduce now.
I think to close this for now. If it can be reproduced I will reopen and upload a sample.

**Comment by j-hudecek** [comment]
Hi, I've just seen the exact same exception on .net core 2.0.6. Have you figured out what was the problem?

	ex: System.InvalidOperationException: The antiforgery token could not be decrypted. ---> System.FormatException: TODO: Malformed input.
		at Microsoft.AspNetCore.WebUtilities.WebEncoders.GetNumBase64PaddingCharsToAddForDecode(Int32 inputLength)
		at Microsoft.AspNetCore.WebUtilities.WebEncoders.GetArraySizeRequiredToDecode(Int32 count)
		at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken) 
	--- End of inner exception stack trace ---
		at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
		at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.DeserializeTokens(HttpContext httpContext, AntiforgeryTokenSet antiforgeryTokenSet, AntiforgeryToken& cookieToken, AntiforgeryToken& requestToken)
		at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.ValidateTokens(HttpContext httpContext, AntiforgeryTokenSet antiforgeryTokenSet)
		at Microsoft.AspNetCore.Antiforgery.Internal.DefaultAntiforgery.d__9.MoveNext() --- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ValidateAntiforgeryTokenAuthorizationFilter.d__3.MoveNext() 
	--- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.d__17.MoveNext() --- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.d__15.MoveNext() --- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at Microsoft.AspNetCore.Builder.RouterMiddleware.d__4.MoveNext() --- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.d__6.MoveNext() --- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.d__3.MoveNext() --- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.d__3.MoveNext() --- End of stack trace from previous location where exception was thrown ---
		at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
		at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
		at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.d__6.MoveNext()

**Comment by verysimplenick** [comment]
I can't reproduce, I don't know that helps, try rebuild and refresh page\token. 
If you running `dotnet watch` - maybe the token is already changed

**Comment by j-hudecek** [comment]
I also can't reproduce it there's thousands of POSTs that go just fine and then there is this one and nothing seems special about it.

**Comment by robertmiles3** [comment]
I just hit this, and can reproduce it. If I submit a form with only a few items in the list selected to update (less form data posting back), then it works fine. If I submit a form with a lot of items selected to update, then it bombs every time. It has something to do with the amount of data posting back. I've tried messing with `FormOptions` and it does no good.

**Comment by robertmiles3** [comment]
Actually, just found the issue, and it wasn't form size related after all. I had accidentally done a nested `<form>` in the list. ASP.NET Core is smart enough to not render that inner `<form>` tag, but it _did_ render extra anti-forgery tokens all throughout the place. I think this was then causing the postback to freak out with all the extras.
